<template>
  <NavBar />
  <div class="container">
    <div class="row mt-4">
      <div class="col">
        <h2>
          List of
          <strong>Beverages</strong>
        </h2>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col">
        <div class="input-group mb-3">
          <input
            v-model="search"
            type="text"
            class="form-control"
            placeholder="Find your coffee..."
            aria-label="Find"
            aria-describedby="basic-addon1"
            @keyup="searchBeverages"
          />
          <!-- v-model="search" two-way data binding betweeninput field and data property named "search" -->
          <!-- @keyup is an event handler "keyup" event on the input field and calls a method named "searchBeverages" -->
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1">
              <i class="bi bi-search"></i>
            </span>
          </div>
        </div>
      </div>
    </div>

    <div class="row mb-4">
      <!-- Desktop -->
      <div
        class="col-md-3 mt-4 d-none d-lg-block"
        v-for="product in products"
        :key="product.id"
      >
      <!-- v-for itu iterates over the products array and assigns each element to the variable product -->
      <!-- :key itu update and manage lists of elements generated by v-for -->
        <CardProduct :product="product" />
        <!-- :product attribute is a prop that passes the product object to the CardProduct component. The product object represents the current item in the iteration from the v-for directive -->
      </div>
      <!-- Medium Screen -->
      <div
        class="col-md-6 mt-4 d-lg-none"
        v-for="product in products"
        :key="product.id"
      >
        <CardProduct :product="product" />
      </div>
    </div>
  </div>
</template>

<script>
import NavBar from "@/components/NavBar.vue";
import CardProduct from "@/components/CardProduct.vue";
import axios from "axios";

export default {
  name: "BeverageList",
  components: {
    NavBar,
    CardProduct,
  },
  data() {
    return {
      //initial state empty array for products, empty string for search
      products: [],
      search: "",
    };
  },
  methods: {
    setProducts(data) {
      this.products = data;
    },
    searchBeverages() {
      axios
        .get("http://localhost:3000/products?q=" + this.search)
        .then((response) => this.setProducts(response.data))
        .catch((error) =>
          console.log("ini error dari search beverages:", error)
        );
    },
  },
  mounted() {
    axios
      .get("http://localhost:3000/products")
      .then((response) => this.setProducts(response.data))
      .catch((error) => console.log("ini error dari get products:", error));
  },
};
</script>

<style></style>
